### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by marvinquiet** [marvinquiet/Cellcano#1]
**Inspired by the newly downloaded mouse brain datasets.**

I use ArchR to process the raw input. For those data provided by SnapATAC, I preprocess the data to 5kb tile matrix and generate ArchR gene score matrix.

- Raw Input format: 
    - `*.fragment.tsv.gz`: fragment file (mostly from 10X platform)
    - `*.bam`: aligned bam file
- Processed Output: 
    - `*.barcodes.tsv.gz`: cell barcode information
    - `*.genescore.mtx.gz`: ArchR best gene score matrix
    - `*.genes.tsv.gz`: genes from gene score matrix

Provide a selection for genome such as mm9, mm10, hg19, hg38 -> we then use the corresponding genomic annotation for the ArchR preprocess

#### 02-01
Finished ArchR preprocessing on fragment file

#### 04-07
- Finished the ArchR preprocessing sub-command line
- Finished training model using KD model
- Figured out how to use logger to generate console/file log

**Comment by atkoriath** [comment]
Do you have any ref_meta.csv files to go with the mouse brain data sets tested in the paper? I am trying to adapt the tutorial to test it on a mouse brain dataset.

**Comment by marvinquiet** [comment]
Hi @atkoriath, thank you for your interest in my work.

May I know which mouse brain dataset are you looking for?

**Comment by atkoriath** [comment]
I was going to use Lareau's Mouse 1 channel 1 data. And how would you suggest creating the ref_meta.csv, does it need to be done manually?

**Comment by marvinquiet** [comment]
Hi @atkoriath,

Got it. For me, I did a bit of manual curation on the cell types to make sure the two datasets are sharing the same cell types. So I only focus on these cell types.

```
dsc_celltype_categories = {'ExNeuron': ["Excite-NEURON"],
                           'InNeuron': ["Inhibit-NEURON"],
                           'Microglia': ["MICROGLIA"],
                           'Endothelial': ["ENDOTHELIAL"],
                           'Astrocyte': ["ASTROCYTE"],
                           'Oligodendrocyte': ["OLIGODENDROCYTE"],
                           'Polydendrocytes': ["POLYDENDROCYTE"]
                           }
``` 
The original metadata should be provided by the author in the supplementary files. If you do not want to process it by yourself, the attached files processed by me should also work. 

[curated_mousebrain_metadata.csv](https://github.com/marvinquiet/Cellcano/files/9699814/curated_mousebrain_metadata.csv)
