### ISSUE TITLE
Can't obtain the example data

### ISSUE THREAD

**Issue by QuietgraceH** [marvinquiet/Cellcano#10]
Hi,Wenjing.Thank you for developing such a great tool.

I am currently using the human immune cell data set provided in the tutorial for testing, but the following three files cannot be downloaded.The web page indicates that the file has been deleted. Is there a new demo file, can you provide a copy, thank you.

#Can't download provided data:
wget https://www.dropbox.com/s/7mdevmylonlh4w4/ref_genescore.csv
wget https://www.dropbox.com/s/18n5wabgg8g2gob/ref_meta.csv
wget https://www.dropbox.com/s/e7g9vem3oxt096l/target_genescore.csv

Sincerely,
Jingya

**Comment by marvinquiet** [comment]
Hi Jingya @QuietgraceH,

Thank you for using my tool and spotting the destroyed links. I have migrated the data and would you please try if the following ones work on your end?

```
wget https://www.dropbox.com/s/tkp60608mm8tdn7/ref_genescore.csv
wget https://www.dropbox.com/s/9mvi4atkn8reddr/ref_meta.csv
wget https://www.dropbox.com/s/l1xxyiu7kk7bafn/target_genescore.csv
``` 

Sorry for the trouble and please let me know if you have any additional questions!

Sincerely,
Wenjing

**Comment by QuietgraceH** [comment]
Thank you wenjing. The link opens fine, but it doesn't have file permissions, I've sent a request for file permissions.

**Comment by marvinquiet** [comment]
Hi Jingya @QuietgraceH,

Thank you for bringing that up! Yes, I have changed the permission for accessing the files. Would you please try again to see if that works?

Sorry for the inconvenience!

Sincerely,
Wenjing

**Comment by QuietgraceH** [comment]
Great!! Thank you for your prompt reply, the file can be downloaded and used normally.

**Comment by marvinquiet** [comment]
Thanks a lot for confirming! Please feel free to let me know if you have any additional questions.
